env:
  browser: true
  es2021: true
extends:
  - 'plugin:react/recommended'
  - airbnb
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
rules:
  {
    'object-curly-newline':
      [
        'error',
        {
          'ObjectExpression': 'always',
          'ObjectPattern': { 'multiline': true },
          'ImportDeclaration': { 'multiline': true },
          'ExportDeclaration': { 'multiline': true, 'minProperties': 3 },
        },
      ],
  }