name: Dev Deploy

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
          cache: 'yarn'
      - run: yarn install --production
      - run: DISABLE_ESLINT_PLUGIN=true yarn test
      - run: DISABLE_ESLINT_PLUGIN=true yarn build
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - run: pip install fabric
      - run: fab -i ${{ secrets.SSH_PRIVATE_KEY }} -H ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST_DEV }}:${{ secrets.REMOTE_PORT }} deploy --branch ${{ env.GITHUB_REF }}
