name: Dev Deploy

on:
  push:
    branches:
      - staging

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
          cache: 'yarn'
      - run: yarn install --production
      - run: DISABLE_ESLINT_PLUGIN=true yarn test --passWithNoTests
      - run: DISABLE_ESLINT_PLUGIN=true yarn build
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir -p /home/runner/.ssh
          ssh-keyscan ${{ secrets.REMOTE_HOST_DEV }} >> /home/runner/.ssh/known_hosts
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > /home/runner/.ssh/ssh_key
          chmod 400 /home/runner/.ssh/ssh_key
      - run: pip install fabric
      - run: fab -i /home/runner/.ssh/ssh_key -H ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST_DEV }}:${{ secrets.REMOTE_PORT }} deploy --branch staging --stage dev
